### ISSUE TITLE
Styled Theme

### ISSUE THREAD

**Issue by jimmynotjim** [wp-evolved/evolved-theme#8]
@germanny and @ericrasch have asked about including a minimum amount of styling in the child theme. I'm thinking maybe we rename the child theme to `evolved-unstyled-theme` and create an `evolved-styled-theme`.

This would allow anyone new to jump in and see real world examples and save everyone else the task of removing unneeded files like we had before. We could also add an option to the generator to allow the user to pick a version during scaffolding (most likely defaulting to the styled version I think).

If we go this way, anyone want to volunteer to duplicate the current child and add some styling? I think we'd also need to be able to import a few test pages/posts. Anyone know where to find some dummy content that's not just lorem or a list of every possible html element?

Any other thoughts?

cc @weeirishman @jameswlane

**Comment by weeirishman** [comment]
Soooo this is dead. 👋
