### ISSUE TITLE
Better Docs/Examples

### ISSUE THREAD

**Issue by jimmynotjim** [wp-evolved/evolved-theme#9]
I know it's a bit of a hurdle getting started with Evolved when you've come from a rigid framework or no css/theme organization at all. I'm going to compile some better docs following thoughtbot's examples but since it's a collection of my own created over two years of projects, I don't always know the gotchas.

@germanny 
@ericrasch 
@weeirishman 
@jameswlane

What were some of the hurdles you experienced that I should include to make it easier for new users?

**Comment by weeirishman** [comment]
dead :dagger:

**Comment by jimmynotjim** [comment]
@weeirishman did you delete your comments? I got them by email but not seeing them here. As of now, yeah, this repo is pretty dead. I haven't done WP development since leaving, so unless someone wants to use it, I don't see anything moving here.

**Comment by weeirishman** [comment]
Yeah I was cleaning up a bunch of old HigherEducation PRs this morning and didn't realize I'd gone from HE's repos over to this one, sorry!  So I re-opened these couple.
